version: '{build}'

image: Visual Studio 2017

environment:
  GENERATOR: "Visual Studio 15 Win64"
  CONFIG: Release

  matrix:
    - PRECISION: -DAS_PRECISION_FLOAT=ON
      ORDER: -DAS_COL_MAJOR=ON
    - PRECISION: -DAS_PRECISION_FLOAT=ON
      ORDER: -DAS_ROW_MAJOR=ON
    - PRECISION: -DAS_PRECISION_DOUBLE=ON
      ORDER: -DAS_COL_MAJOR=ON
    - PRECISION: -DAS_PRECISION_DOUBLE=ON
      ORDER: -DAS_ROW_MAJOR=ON

build_script:
- mkdir catch2 && cd catch2
- git clone --depth=10 --branch=master https://github.com/catchorg/Catch2.git .
- mkdir build && cd build
- cmake -G "%GENERATOR%" -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=../../tests/build/catch2_install/ ..
- cmake --build . --config "%CONFIG%" --target install
- cd ../..
- mkdir build && cd build
- cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=../tests/build/as_install/ ..
- cmake --build . --target install --config "%CONFIG%"
- cd ../tests/build
- cmake -G "%GENERATOR%" "%PRECISION%" "%ORDER%" -DDEV_LIB_DIR=../../ .. -DCMAKE_PREFIX_PATH=%cd%\catch2_install;%cd%\as_install
- cmake --build . --config "%CONFIG%"
- "\"%CONFIG%\"\\as-test.exe"
