os: linux
dist: trusty
language: cpp
notifications:
  email: false
matrix:
  include:
  - env: 'C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Debug PRECISION="-DAS_PRECISION_FLOAT=ON"
      ORDER="-DAS_COL_MAJOR=ON"

'
    addons: &1
      apt:
        packages:
        - clang-5.0
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main
          key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
  - env: 'C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Release PRECISION="-DAS_PRECISION_FLOAT=ON"
      ORDER="-DAS_COL_MAJOR=ON"

'
    addons: *1
  - env: 'C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Debug PRECISION="-DAS_PRECISION_FLOAT=ON"
      ORDER="-DAS_ROW_MAJOR=ON"

'
    addons: *1
  - env: 'C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Release PRECISION=-DAS_PRECISION_DOUBLE=ON
      ORDER="-DAS_ROW_MAJOR=ON"

'
    addons: *1
  - env: 'C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BUILD_TYPE=Debug PRECISION="-DAS_PRECISION_FLOAT=ON"
      ORDER="-DAS_COL_MAJOR=ON" COVERAGE="-DAS_COVERAGE=ON"

'
    addons: &2
      apt:
        packages:
        - g++-7
        - lcov
        sources:
        - ubuntu-toolchain-r-test
  - env: 'C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BUILD_TYPE=Release PRECISION="-DAS_PRECISION_FLOAT=ON"
      ORDER="-DAS_COL_MAJOR=ON" COVERAGE="-DAS_COVERAGE=ON"

'
    addons: *2
  - env: 'C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BUILD_TYPE=Debug PRECISION="-DAS_PRECISION_FLOAT=ON"
      ORDER="-DAS_ROW_MAJOR=ON" COVERAGE="-DAS_COVERAGE=ON"

'
    addons: *2
  - env: 'C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BUILD_TYPE=Release PRECISION=-DAS_PRECISION_DOUBLE=ON
      ORDER="-DAS_COL_MAJOR=ON" COVERAGE="-DAS_COVERAGE=ON"

'
    addons: *2
install:
- export CC=${C_COMPILER}
- export CXX=${CXX_COMPILER}
- "${CXX} --version"
- JOBS=2
- gem install coveralls-lcov
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
- travis_retry wget https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6-Linux-x86_64.tar.gz
- tar -xvf cmake-3.16.6-Linux-x86_64.tar.gz > /dev/null
- mv cmake-3.16.6-Linux-x86_64 cmake-install
- PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
- cd ${TRAVIS_BUILD_DIR}
before_script:
- tools/install-catch2.sh
- tools/install-gsl.sh
- tools/install-as.sh
- cd tests/test
- 'cmake -S . -B build -DCATCH_CONFIG_DISABLE_EXCEPTIONS=1 -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  -DCMAKE_PREFIX_PATH=$(pwd)/build/as_install/\;$(pwd)/build/catch2_install/\;$(pwd)/build/gsl_install/
  ${PRECISION} ${ORDER} ${COVERAGE}

'
script:
- cmake --build build -j${JOBS} -v
- "./build/as-test"
after_success:
- |
  if [ $BUILD_TYPE == "Debug" ] && [ $CXX_COMPILER == "g++-7" ]; then
    lcov --capture --directory build --output-file coverage.info --gcov-tool=gcov-7
    lcov --remove coverage.info '*/gsl_install/*' '*/catch2/*' '*/7.4.0/*' '*/usr/include/*' '*/tests/test/*.test.*' '*/tests/test/catch-*' --output-file coverage.info --gcov-tool=gcov-7 # filter external files
    lcov --list coverage.info --gcov-tool=gcov-7 # debug info
    # codecov
    bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports" # uploading report to codecov
    # coveralls
    coveralls-lcov coverage.info
    # codacy
    bash <(curl -Ls https://coverage.codacy.com/get.sh) report --language cpp --force-language -r coverage.info
  fi
env:
  global:
  - secure: tZpXm07YMRboP1ba7w55Akis5vaUQaIw/Yn75rc39kzEqAtiJhsJ0BW5ZBBRGfSiszGKCccl7NgDiTWa7JTM9W0TAyAFuASEy4+Kp0iLVXb2AIXyPhz/k+Foh1gZ3lrYDJ1V/Lsi6MSLBoOHj6ir34PRqsrvs5H3mSg9YEw2h0HPQPhxIaXxg9mYNK2Wjkn0aKy7jQCvbkCSFuAWbdQr1CGSohTXfkwDikFFXqiJF8ydRXlv6Kc7l/nJnC32S9f2lripzx7ce3YMUpYF9I6UOMG2FB03zsh5EFIMY3i36wUbUupCK8J9UP7zqzii387D3h5X1i3xiga9QLW6AVODNrLYc2ZdKdBO10CvjpbB6DkRhnLiO70yyA2sPi364loS8OodCH67JM+AgjUY+WWRsfLrjhPdUY6D14pwo5vQap32QLuv42PfWUTI3FQ8PJPQi/0pEQii2kT05Uj6EFFKr0c6eY/ZX1siJwBKis1M97DtNBRhIpI873fybLaOl/+4iaeBWIojsmWJUrT9pSJZSiPPqF2ukY/aPb5/fvAoVARa+6zNVk4c7p+U0oIyrT/r5KxtC+JK8LhG2DczdUuC1VodHH3oc7UVaQUzZzPUPeVN3Y9pxGdyThqbjdPuIphx9ufs2/uCW7A2SmRWS/4RH5KdnMd68uxTgGF6LxqCnbE=
